### PR TITLE
Add TurboGraFX TurboPad Controllers

### PR DESCRIPTION
**Pull request by munskey**
Add TurboGraFX controller: 
controller3.svg
controller4.svg

### CODE REVIEW

**Comment by paradadf** [comment]
What's the point right now to add these but still havin the pc engine console? Moreover, I think my version is better XD.
There are plans of adding a switch to change the themes according to different regions...
https://github.com/recalbox/recalbox-themes/issues/131
I would recommend you to wait until it is implemented and again (sorry), I still think my version is better.

**Comment by munskey** [comment]
I made these files a couple months back when I updated the SNES and Super Famicom controllers that your thread links to and is using.  Just now getting around to merging them.

I feel mine are more accurate to the physical controller (Text size and position, color, D-Pad size, etc.) while adhering to the look/feel of the RecalBox theme, i.e. no gradients - flat style.

**Comment by paradadf** [comment]
Afaik the "no gradients" itself is just a "rule" because ES can't render them properly. I didn't use gradients for mines, but the effect of a gradient. About the colors... Sometimes you don't have the necessary contrast with the "original" colors that allow the image and details to be nicely shown on ESAnd the colors also varies from picture to picture you ger on the internet.

**Comment by rockaddicted** [comment]
Hi @munskey and thank you for this PR.
I won't merge it, because for the moment, we don't have a way to differentiate the systems proper to each area.
We'll keep the pcengine theme "clean" then, once the areas switch (EU/US/JP) added in ES, we could add new, specific systems proper to each area, as turbographx instead of pcengine.

**Pull request closed without merging**
