### PR TITLE
Resources for ZX81 and ZX Spectrum

### PR DESCRIPTION
**Pull request by zarroun**
Let me know if something needs changing.

### CODE REVIEW

**Comment by rockaddicted** [comment]
Good job, thank you :wink:

**Comment by zarroun** [comment]
My thanks to you.
Do we also send you music suggestions or are you set on that front?

**Comment by digitalLumberjack** [comment]
The musics for the new theme are not associated to the system your are browsing. We are working with people creating original compositions for the recalbox, based on well known video game musics :)

**Comment by zarroun** [comment]
OH DUDE, that is FREAKING AWESOME!!! Wow, so incredibly looking forward to this release. Hope to get the time in for a few more contributions.

**Comment by digitalLumberjack** [comment]
That would be very nice of you :)

**Pull request merged**
