### PR TITLE
Partial Genesis and TG16 (North American) theme

### PR DESCRIPTION
**Pull request by ghost**
created theme folders for genesis and tg16. changed logo reference in theme.xml to use North American logos for each.

updates still needed for: 
genesis/data/console.svg
genesis/data/controller.svg
genesis/data/controller2.svg
genesis/data/game.svg

tg16/data/console.svg

### CODE REVIEW

**Comment by paradadf** [comment]
Why are you adding (needlessly) Megadrive/PC Engine stuff to the Genesis/Turbografx 16 folder you want to create? The only complicated part (speaking about themes) of adding a new system is vectorizing the images.

**Comment by ghost** [comment]
I just copied over the entire megadrive folder to genesis and likewise for pcengine to tg16.

I left all the files alone with the exception of editing the theme.xml file to display the NA logos. I figured leaving the other files would keep the theme complete even if it mixed megadrive with genesis and pcengine with tg16 until someone has a chance to create the proper vector graphics.

**Comment by paradadf** [comment]
Why don't you first discuss the adding of extra themes in the blog or as an issue, instead of making a sort of "dirty" pull request? Nobody will invest time vectorizing the images if the work will be in vane.
And only to be clear, I say "dirty" meaning that you should have add only the correct logos if they are already available instead of copying the entire folder (e.g. changing logo2.svg to logo.svg). The other still not vectorized images can then easily be overwritten.

**Comment by ghost** [comment]
maybe I jumped ahead a little bit but I did add issue #131 which has a discussion ongoing.

**Comment by paradadf** [comment]
I had seen the the issue. And I actually agree to it and would, when I have time, help with the drawings. But don't rush so much ;)

**Comment by paradadf** [comment]
@jaykass I think it would be better to close your PR and wait until it is decided exactly how this would be done. I will little by little work on vectorizing the different systems and present them to the issue opened.

**Pull request closed without merging**
