### PR TITLE
Add pc system to RecalBox theme (for DosBox)

### PR DESCRIPTION
**Pull request by lmerckx**
Largely inspired from ScummVM one (I confess)

### CODE REVIEW

**Comment by rockaddicted** [comment]
haha Thanks dude :wink:

**Comment by rockaddicted** [comment]
Could you add too your ressources files, please ? (.ai, etc...)

**Comment by lmerckx** [comment]
Oh. In fact, I haven't.
I directly edited the SVG files of scummvm to adapt them.

Sorry.

**Comment by rockaddicted** [comment]
haha no problem.

**Pull request merged**
