### PR TITLE
4.0.x Pixel Theme

### PR DESCRIPTION
**Pull request by mgoulartBR**
Hi again,

I discovered this theme today and I liked it! So a modified it in order to run on RecalboxOS.
Could you test for a future release?
[pixel.zip](https://github.com/recalbox/recalbox-themes/files/239605/pixel.zip)

### CODE REVIEW

**Comment by rockaddicted** [comment]
Thanks @mgoulartBR I'll try it :wink:

**Comment by rockaddicted** [comment]
So I tested this theme.
It is looks pretty good with an oldschool / pixel art style.
But too keep this design, we must work recalbox's systems (screenshots, favorites etc ...) in a pixel art spirit.
So we won't add it for now, but once the others themes will be OK, why not work on this one.

I close this PR, and when we'll start to work on this theme, I'll add it on the repo.

**Comment by mgoulartBR** [comment]
I aggree! Thx!

**Comment by mgoulartBR** [comment]
logo

Is it good or need more pixels?

**Pull request closed without merging**
