### PR TITLE
Change defaults consoles for fba, fba_libretro and mame

### PR DESCRIPTION
**Pull request by paradadf**
This PR is just a suggestion, as I consider the version I did better looking for Recalbox.
But don't worry, I won't take any offense if you don't want to change the default svg files.

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
@rockaddicted @reivaax what do you think about that ?

**Comment by Supernature2k** [comment]
I totally agree with you @paradadf and I use these ones in my themes.
Only problem is size of the donkey kong one because of the "screenshot" in it.

**Comment by paradadf** [comment]
@Supernature2k not anymore... It wasn't using a screenshot, but a compound drawing that was super heavy. I drew a new one a couple of weeks ago to correct it and it is already part of Recalbox. 
See https://github.com/recalbox/recalbox-themes/commit/8cf40e2e9709050638ff23f9cbc54ca5e46b5117

**Comment by rockaddicted** [comment]
I'm ok to use theses ones by default.
And you @reivaax ?

**Comment by digitalLumberjack** [comment]
@reivaax at your go we'll merge.

**Comment by reivaax** [comment]
Hum @digitalLumberjack @paradadf  and @rockaddicted, I'm not for this Pull request. If you @paradadf you have "any offense if you don't want to change the default svg files", for me it's not the same. Remember it's my work you want change !!!! :D.

No it's a joke ^^. Your work is more in the spirit of the theme.
No problem for me but i tinks it's better to rename the svg files... For kip the same structure on all the systems... _(file one is the default file... File1, file2, file3, ... are the possibility...)_.

**Comment by paradadf** [comment]
I talked a bit with rockaddicted about the naming issue. He also thinks there is a need for a clean up of names, but better to do it together with the alternative region switch to have it done only once.

**Comment by reivaax** [comment]
@paradadf. Yes, i tink we need to explore the multi template of @Supernature2k for alternatives , screen size, system view, region visual, svg alternative, color,... :). I tinks it's the best solution for give a maximum of possibility in the same template...

**Comment by paradadf** [comment]
well... in the meanwhile can this be merged?

**Pull request merged**
