### PR TITLE
4.0.x Eudora Bigshot Theme

### PR DESCRIPTION
**Pull request by mgoulartBR**
Hi guys,

I just finished the settings to run Eudora Theme on Recalbox. Please I would like to ask for it on a future Recalbox release.

[eudora-bigshot.zip](https://github.com/recalbox/recalbox-themes/files/233632/eudora-bigshot.zip)

### CODE REVIEW

**Comment by rockaddicted** [comment]
Hi @mgoulartBR,
I tested your theme on my recalbox 4.0.0 beta3. 
So eudora theme look great, thank you for this conversion. 
But there is missing systems in this theme.

I added in the first page of this repository, the systems list to support in a theme, to have it compatible with recalboxOS.
So if you want, I can add, your actual theme version to the repository, and you update/add the missing systems using github.

Are you ok with that ?

**Comment by mgoulartBR** [comment]
Sure!!! I will check it out! I thought that I included all the systems supported by Recalbox!

**Comment by rockaddicted** [comment]
Ok great. So I'll close this PR, add the eudora theme to the repository and wait your pull requests :wink:

**Comment by mgoulartBR** [comment]
[eudora-bigshot.zip](https://github.com/recalbox/recalbox-themes/files/237706/eudora-bigshot.zip)

Now it's okay! :)

**Pull request closed without merging**
